Traceback (most recent call last):
  File "c:\Users\Wesley\Documents\GitHub\My-automative-python-code\Chapter10\errorExample.py", line 15, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
